import { useI18n } from '../i18n'
import { feePercentage } from '../api/dataCenter'
export function useQuantText(){const {language}=useI18n();return (zh:string,en:string)=>language==='zh'?zh:en}
export const quantPercent=(v:string|null|undefined)=>v==null?'…':feePercentage(v)
const labels:Record<string,[string,string]>={
 etf_momentum:['ETF 动量轮动','ETF momentum rotation'],ma_trend:['均线趋势','Moving-average trend'],etf_mean_reversion:['ETF 均值回归','ETF mean reversion'],
 lookback:['动量回看期（交易日）','Momentum lookback (sessions)'],top_k:['最多持有标的数','Maximum selected instruments'],rebalance_every:['调仓间隔（交易日）','Rebalance interval (sessions)'],ma_window:['均线窗口（交易日）','Moving-average window (sessions)'],entry_deviation:['买入偏离阈值（比率）','Entry deviation (ratio)'],exit_deviation:['退出偏离阈值（比率）','Exit deviation (ratio)'],
 commission_rate:['佣金比率','Commission ratio'],minimum_commission:['最低佣金（CNY）','Minimum commission (CNY)'],sell_tax:['A 股卖出税比率','A-share sell tax ratio'],slippage:['滑点比率','Slippage ratio'],volume_cap:['前日成交量参与上限','Prior-session volume participation cap'],
 net_return:['净收益','Net return'],gross_return:['零成本收益','Costless return'],annualized_sample_volatility:['年化样本波动率','Annualized sample volatility'],max_drawdown:['最大回撤','Maximum drawdown'],turnover:['成交额 / 初始现金','Traded notional / initial cash'],average_exposure:['平均风险敞口','Average exposure'],fees_paid:['累计费用（CNY）','Fees paid (CNY)'],sample_count:['观测交易日数','Observed sessions'],end_nav:['期末资产（CNY）','Ending NAV (CNY)'],
 unknown:['未知公司行动覆盖','Unknown corporate-action coverage'],declared_complete:['用户声明行动覆盖完整','User-declared complete action coverage'],declared_none:['用户声明无公司行动','User-declared no corporate actions'],
 insufficient_prior_closes:['历史收盘价不足，正在预热','Insufficient prior closes, warming up'],missing_signal_bar:['信号窗口缺失行情','Missing bars in signal window'],invalid_action_price_adjustment:['公司行动价格调整不可用','Action price adjustment unavailable'],same_universe_hold_baseline:['同范围买入持有基线','Same-universe hold baseline'],
 missing_open_bar:['缺失开盘行情','Missing opening bar'],zero_volume_halt:['当日零成交量，模拟停牌拒绝','Zero current volume, simulated halt'],missing_previous_bar_for_capacity:['缺少前日成交量','Missing previous bar for capacity'],missing_previous_close_for_limit:['缺少前日收盘价','Missing previous close for price limits'],buy_limit_up:['开盘触及买入涨幅上限','Opening buy price limit'],sell_limit_down:['开盘触及卖出跌幅上限','Opening sell price limit'],price_limit:['触及声明价格限制','Declared price limit'],insufficient_cash:['现金不足','Insufficient cash'],settlement_unavailable:['结算限制，数量不可卖','Settlement quantity unavailable'],lot_rounding:['不足一手交易单位','Below trading lot'],
 instrument_rules_are_user_assumptions_not_certified_historical_rules:['交易单位、结算与涨跌限制为用户假设，未经历史交易所核验。','Lot, settlement and price limits are user assumptions, not certified historical rules.'],calendar_is_observed_or_user_declared_not_certified_exchange_history:['日历来自观察或用户声明，不代表完整交易所日历。','Calendar is observed or user declared, not certified exchange history.'],daily_open_fill_and_zero_volume_halt_are_execution_approximations:['日线开盘成交与零成交量停牌属于执行模拟近似。','Daily opening fills and zero-volume halts are execution approximations.'],constant_a_share_tax_assumption_not_historical_policy_schedule:['A 股税率使用固定假设；ETF / LOF 不收取该税，不复原历史税制。','A-share sell tax uses a constant assumption; ETF/LOF are exempt, with no reconstructed historical tax schedule.'],unknown_corporate_actions_research_price_return_only:['公司行动覆盖未知，结果仅用于价格收益研究。','Corporate actions are unknown; results are price-return research only.'],corporate_action_coverage_is_user_declaration_not_verified_total_return:['公司行动覆盖为用户声明，不构成已核验总收益。','Action coverage is user declared, not verified total return.'],some_price_limit_assumptions_unspecified:['部分标的未设置涨跌限制假设。','Some price-limit assumptions are unspecified.'],missing_bars_not_tradable_last_known_valuation_stale:['缺失行情不可交易，沿用旧价格的估值标为过期。','Missing bars cannot trade; last-known valuations are marked stale.'],holdout_insufficient_signal_history_robustness_unavailable:['样本外历史不足，稳健性诊断不可用。','Held-out signal history is insufficient; robustness is unavailable.'],saved_quote_freshness_not_certified:['实际持仓使用本地保存报价，时效未经核验。','Actual holdings use locally saved quotes with uncertified freshness.'],weights_over_known_valuations_only:['实际权重分母只包含已知估值。','Actual weights use known valuations only.'],
 one_sided_price_limit:['触及声明的单边价格限制','Declared one-sided price limit'],volume_cap_partial:['成交量上限导致部分拒绝','Partial rejection at volume cap'],settlement_lag_partial:['结算延迟导致部分数量不可卖','Partial quantity unavailable for settlement'],insufficient_cash_partial:['现金不足导致部分拒绝','Partial rejection for insufficient cash'],below_lot_or_unavailable_cash:['不足一手或现金不可用','Below lot or cash unavailable'],insufficient_cash_for_sell_fee:['卖出费用所需现金不足','Insufficient cash for sell fees'],
 unsupported_fact:['事实陈述缺少直接证据','Fact claim lacks direct evidence'],numeric_mismatch:['报告数值与冻结值不一致','Reported and frozen numbers differ'],metric_unavailable:['所引用指标不可用','Referenced metric unavailable'],title_only_numeric_fact_unsupported:['标题证据不足以支持数值事实','Title-only evidence cannot support a numeric fact'],
 diagnostic:['稳健性诊断','Robustness diagnostic'],
 buy:['买入','Buy'],sell:['卖出','Sell'],warmup:['预热','Warmup'],ready:['就绪','Ready'],unavailable:['不可用','Unavailable'],completed:['已完成','Completed'],failed:['失败','Failed'],awaiting_future_data:['等待后续行情','Awaiting future data'],active:['跟踪中','Active'],unreviewed:['未复核','Unreviewed'],reviewed:['已复核','Reviewed'],invalidated:['已失效','Invalidated'],matched:['数值一致','Numeric match'],mismatch:['数值不一致','Numeric mismatch'],not_reported:['未报告数值','Not reported'],passed:['引用存在','References exist'],not_assessed:['未评估','Not assessed'],supported:['模型认为有支持','Model: supported'],unsupported:['模型认为无支持','Model: unsupported'],uncertain:['模型认为不确定','Model: uncertain'],fact:['事实陈述','Fact claim'],inference:['分析推断','Inference'],hypothesis:['待验证假设','Hypothesis'],
}
export function useQuantLabel(){const q=useQuantText();return (v:string)=>labels[v]?q(...labels[v]):v.replace(/_/g,' ')}
