import {afterEach,describe,expect,it,vi} from 'vitest'
import * as q from './quant'
import {quantAccount,quantComparison,quantDataset,quantDatasetSummary,quantResearch,quantRun,quantRunSummary,quantStrategy,quantSummary,quantTemplates} from '../test/quantFixtures'
const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v))
afterEach(()=>vi.unstubAllGlobals())
describe('quant lossless contracts',()=>{
 it('accepts the bounded multiple-rejection-per-asset-session no-fill case',()=>{const r=clone(quantRun);r.result.fills=[];r.result.rejections=Array.from({length:14400},()=>({...quantRun.result.rejections[0]}));expect(q.validateRun(r).result.rejections).toHaveLength(14400);r.result.rejections.push({...quantRun.result.rejections[0]});expect(()=>q.validateRun(r)).toThrow(q.QuantError)})
 it('rejects arbitrary import fields and malformed model references',()=>{const {id,fingerprint,created_at,warnings,...body}=quantDataset;void id;void fingerprint;void created_at;void warnings;expect(()=>q.parseDatasetImport(JSON.stringify({...body,url:'https://arbitrary.example'}))).toThrow(q.QuantError);const a=clone(quantResearch);a.research!.claims[0].evidence_ids=['missing'];expect(()=>q.validateAnnotation(a,1)).toThrow(q.QuantError);const b=clone(quantResearch);b.research!.claims[0].metric_refs[0].metric_key='missing';expect(()=>q.validateAnnotation(b,1)).toThrow(q.QuantError)})

 it('accepts flat frozen API envelopes and retains exact decimals',()=>{
  expect(q.validateTemplates(quantTemplates)).toEqual(quantTemplates)
  expect(q.validateDataset(quantDataset).bars?.[0].open).toBe('4.0000000000000000001')
  expect(q.validateDataset(quantDatasetSummary).session_count).toBe(6)
  expect(q.validateStrategy(quantStrategy).parent_id).toBeNull()
  expect(q.validateRun(quantRun).result.metrics.net_return).toBe('0.012345678901234567890123')
  expect(q.validateRunSummary(quantRunSummary).id).toBe(1)
  expect(q.validateAccount(quantAccount).version).toBe(1)
  expect(q.validateComparison(quantComparison,1).rows[0].quantity).toBe('10.00000000000000001')
  expect(q.validateSummary(quantSummary).mode).toBe('paper_only')
 })
 it.each(['numeric','nonfinite','missing','wrong-id','same-close-fill','missing-signal-inputs'] as const)('rejects %s frozen run defects',type=>{const r=clone(quantRun);if(type==='numeric')(r.result.metrics as unknown as {net_return:number}).net_return=0.1;if(type==='nonfinite')r.result.metrics.net_return='NaN';if(type==='missing')delete (r.result as Partial<typeof r.result>).metrics;if(type==='wrong-id')r.id=3;if(type==='same-close-fill')r.result.fills[0].signal_date=r.result.fills[0].date;if(type==='missing-signal-inputs')delete r.result.signals[1].inputs;expect(()=>q.validateRun(r,1)).toThrow(q.QuantError)})
 it('validates object/version identity before exposing account or comparison',()=>{expect(()=>q.validateAccount({...quantAccount,version:0})).toThrow(q.QuantError);expect(()=>q.validateAccount(quantAccount,2)).toThrow(q.QuantError);expect(()=>q.validateComparison(quantComparison,2)).toThrow(q.QuantError)})
 it('validates bounded raw JSON imports without changing decimal strings',()=>{const {id,fingerprint,created_at,warnings,...body}=quantDataset;void id;void fingerprint;void created_at;void warnings;expect(q.parseDatasetImport(JSON.stringify(body)).bars[0].open).toBe('4.0000000000000000001');expect(()=>q.parseDatasetImport(JSON.stringify({...body,price_basis:'adjusted'}))).toThrow(q.QuantError);expect(()=>q.parseDatasetImport(JSON.stringify({...body,bars:[...body.bars!,body.bars![0]]}))).toThrow(q.QuantError);expect(()=>q.parseDatasetImport(JSON.stringify({...body,calendar:['2026-01-06','2026-01-05']}))).toThrow(q.QuantError);expect(()=>q.parseDatasetImport(' '.repeat(2000001))).toThrow(q.QuantError)})
 it('degrades duplicate optional critique to unavailable without altering primary or stored payload',()=>{const a=clone(quantResearch);a.model_review={status:'available',label:'model_review_not_verification',claims:[{claim_index:0,support:'supported',explanation:'First'},{claim_index:0,support:'unsupported',explanation:'Second'}]};const validated=q.validateAnnotation(a,1);expect(validated.research).toEqual(a.research);expect(validated.model_review?.status).toBe('unavailable');expect(validated.model_review?.claims).toBeUndefined();expect(a.model_review.status).toBe('available');const r=q.validateRun({...quantRun,annotations:[a]});expect(r.annotations?.[0].model_review?.status).toBe('unavailable')})
 it('preserves abort ownership and exact request decimal bodies',async()=>{const fetch=vi.fn().mockResolvedValue({ok:true,json:async()=>quantRun});vi.stubGlobal('fetch',fetch);const c=new AbortController();const cash='100000.00000000000000001';await q.createQuantRun({strategy_id:1,dataset_id:1,initial_cash:cash,costs:quantAccount.costs},c.signal);expect(fetch.mock.calls[0][1].signal).toBe(c.signal);expect(JSON.parse(fetch.mock.calls[0][1].body).initial_cash).toBe(cash);const pending=q.fetchQuantRun(1,c.signal);c.abort();await expect(pending).rejects.toMatchObject({name:'AbortError'})})
 it.each([[409,'conflict'],[422,'invalid'],[404,'missing'],[502,'source'],[500,'request']] as const)('uses controlled HTTP %s without leaking provider content',async(status,code)=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:false,status,json:async()=>({detail:'secret provider body'})}));await expect(q.fetchQuantRun(1)).rejects.toMatchObject({code,message:code})})
 it('rejects duplicate list IDs and validates exact detail identity',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>[quantStrategy,quantStrategy]}));await expect(q.fetchQuantStrategies()).rejects.toMatchObject({code:'payload'});vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({...quantRun,id:2})}));await expect(q.fetchQuantRun(1)).rejects.toMatchObject({code:'payload'})})
})
