import type {Account, Acquire, Annotation, Comparison, Costs, Dataset, DatasetImport, ReviewBody, Run, RunBody, RunSummary, Strategy, StrategyBody, Summary, Templates} from '../types/quant'
export class QuantError extends Error {constructor(public readonly code:'payload'|'network'|'request'|'conflict'|'invalid'|'missing'|'source'){super(code)}}
const fail=():never=>{throw new QuantError('payload')}
const object=(v:unknown):Record<string,unknown>=>{if(!v||typeof v!=='object'||Array.isArray(v))return fail();return v as Record<string,unknown>}
const text=(v:unknown,max=4000,empty=false)=>{if(typeof v!=='string'||v.length>max||(!empty&&!v.length))fail()}
const integer=(v:unknown,min=1)=>{if(!Number.isSafeInteger(v)||(v as number)<min)fail()}
const choice=(v:unknown,values:string[])=>{if(!values.includes(v as string))fail()}
const array=(v:unknown,max:number,check:(v:unknown)=>unknown):unknown[]=>{if(!Array.isArray(v)||v.length>max)return fail();v.forEach(check);return v}
const dates=(v:unknown)=>{if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v)fail()}
export const isQuantDecimal=(v:unknown):v is string=>typeof v==='string'&&v.length<=100&&/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?$/.test(v)&&Number.isFinite(Number(v))
const importKeys=(v:Record<string,unknown>,keys:string[])=>{if(Object.keys(v).some(k=>!keys.includes(k)))fail()}
const inputDecimal=(v:unknown)=>{decimal(v);if((v as string).length>60||Math.abs(Number(v))>1e15||(Number(v)!==0&&Math.abs(Number(v))<1e-20))fail()}
const shanghaiDay=()=>{const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());return ['year','month','day'].map(k=>p.find(x=>x.type===k)?.value).join('-')}
const decimal=(v:unknown)=>{if(!isQuantDecimal(v))fail()}
const nullableDecimal=(v:unknown)=>{if(v!==null)decimal(v)}
const strings=(v:unknown,max=100)=>array(v,max,x=>text(x))
const ids=(v:unknown,max=8)=>{const a=array(v,max,x=>integer(x));if(new Set(a).size!==a.length)fail();return a}
const fp=(v:unknown)=>{if(typeof v!=='string'||!/^[a-f0-9]{64}$/.test(v))fail()}
function envelope(v:unknown,id?:number){const o=object(v);integer(o.id);text(o.created_at);if(id!==undefined&&o.id!==id)fail();return o}
function costs(v:unknown){const o=object(v);['commission_rate','minimum_commission','sell_tax','slippage','volume_cap'].forEach(k=>decimal(o[k]))}
function instrument(v:unknown){const o=object(v);integer(o.security_id);choice(o.market,['SH','SZ']);if(typeof o.code!=='string'||!/^\d{6}$/.test(o.code))fail();text(o.name,100);choice(o.instrument_type,['a_share','etf','lof']);integer(o.lot_size);integer(o.settlement_lag,0);if((o.settlement_lag as number)>1)fail();nullableDecimal(o.limit_pct)}
function strategyBody(v:unknown){const o=object(v);text(o.name,100);choice(o.template,['etf_momentum','ma_trend','etf_mean_reversion']);const a=ids(o.universe);if(!a.length)fail();decimal(o.max_exposure);const p=object(o.parameters);const expected=o.template==='etf_momentum'?['lookback','top_k','rebalance_every']:o.template==='ma_trend'?['ma_window','rebalance_every']:['ma_window','rebalance_every','entry_deviation','exit_deviation'];if(Object.keys(p).some(k=>!expected.includes(k)))fail();expected.forEach(k=>k.includes('deviation')?decimal(p[k]):integer(p[k]));if(o.parent_id!==undefined&&o.parent_id!==null)integer(o.parent_id)}
export function validateStrategy(v:unknown,id?:number):Strategy{const o=envelope(v,id);fp(o.fingerprint);strategyBody(o);if(o.parent_id!==null)integer(o.parent_id);return v as Strategy}
function bar(v:unknown){const o=object(v);integer(o.security_id);dates(o.date);['open','high','low','close','volume'].forEach(k=>decimal(o[k]));if(['open','high','low','close'].some(k=>Number(o[k])<=0)||Number(o.volume)<0||Number(o.low)>Math.min(Number(o.open),Number(o.close))||Number(o.high)<Math.max(Number(o.open),Number(o.close)))fail()}
function action(v:unknown){const o=object(v);integer(o.security_id);dates(o.date);choice(o.kind,['split','cash_dividend']);decimal(o.value);if(Number(o.value)<=0)fail();if(o.kind==='cash_dividend'){dates(o.cash_available_date);if((o.cash_available_date as string)<(o.date as string))fail()}else if(o.cash_available_date!==undefined&&o.cash_available_date!==null)fail()}
function datasetFields(o:Record<string,unknown>,full:boolean){text(o.name,100);text(o.source,100);text(o.retrieved_at);choice(o.price_basis,['raw']);choice(o.currency,['CNY']);choice(o.volume_unit,['shares']);const instruments=array(o.instruments,8,instrument);if(!instruments.length)fail();ids(instruments.map(i=>object(i).security_id));choice(o.corporate_action_coverage,['unknown','declared_complete','declared_none']);if(o.calendar_provenance!==undefined)text(o.calendar_provenance,200);if(full){const calendar=array(o.calendar,600,dates) as string[];if(calendar.length<2||calendar.some((d,i)=>i>0&&d<=calendar[i-1]))fail();const bars=array(o.bars,4800,bar);if(bars.length<2)fail();const universe=new Set(instruments.map(i=>object(i).security_id));const pairs=bars.map(b=>{const x=object(b);if(!universe.has(x.security_id)||!calendar.includes(x.date as string))fail();return `${x.security_id}:${x.date}`});if(new Set(pairs).size!==pairs.length)fail();const actions=array(o.actions,100,action);if(o.corporate_action_coverage==='declared_none'&&actions.length)fail();actions.forEach(a=>{const x=object(a);if(!universe.has(x.security_id)||!calendar.includes(x.date as string)||(x.cash_available_date&&!calendar.includes(x.cash_available_date as string)))fail()})}else{integer(o.bar_count,0);integer(o.session_count,2);dates(o.coverage_start);dates(o.coverage_end)}}
export function validateDataset(v:unknown,id?:number):Dataset{const o=envelope(v,id);fp(o.fingerprint);datasetFields(o,o.bars!==undefined);strings(o.warnings);return v as Dataset}
export function parseDatasetImport(raw:string):DatasetImport{if(new TextEncoder().encode(raw).length>2000000)throw new QuantError('invalid');let v:unknown;try{v=JSON.parse(raw)}catch{throw new QuantError('invalid')}try{const o=object(v);importKeys(o,['name','source','retrieved_at','price_basis','currency','volume_unit','calendar','instruments','bars','corporate_action_coverage','actions','calendar_provenance']);datasetFields(o,true);(o.instruments as unknown[]).forEach(v=>{const i=object(v);importKeys(i,['security_id','market','code','name','instrument_type','lot_size','settlement_lag','limit_pct']);if((i.lot_size as number)>10000)fail();if(i.limit_pct!==null){inputDecimal(i.limit_pct);if(Number(i.limit_pct)<=0||Number(i.limit_pct)>1)fail()}});(o.bars as unknown[]).forEach(v=>{const b=object(v);importKeys(b,['security_id','date','open','high','low','close','volume']);['open','high','low','close','volume'].forEach(k=>inputDecimal(b[k]))});(o.actions as unknown[]).forEach(v=>{const a=object(v);importKeys(a,['security_id','date','kind','value','cash_available_date']);inputDecimal(a.value)});const actionKeys=(o.actions as unknown[]).map(v=>{const a=object(v);return `${a.security_id}:${a.date}:${a.kind}`});if(new Set(actionKeys).size!==actionKeys.length)fail();const timestamp=o.retrieved_at as string;if(!/(Z|[+-]\d{2}:\d{2})$/.test(timestamp)||!Number.isFinite(Date.parse(timestamp))||Date.parse(timestamp)>Date.now())fail();if((o.calendar as string[]).some(d=>d>shanghaiDay()))fail();return v as DatasetImport}catch{throw new QuantError('invalid')}}
function metrics(v:unknown){const o=object(v);['net_return','max_drawdown','turnover','average_exposure','fees_paid','end_nav'].forEach(k=>decimal(o[k]));nullableDecimal(o.annualized_sample_volatility);integer(o.sample_count,0);if(o.gross_return!==undefined)decimal(o.gross_return)}
function equity(v:unknown){const o=object(v);dates(o.date);['nav','cash','exposure'].forEach(k=>decimal(o[k]));ids(o.stale_security_ids)}
function signal(v:unknown){const o=object(v);dates(o.date);choice(o.status,['ready','warmup','unavailable']);text(o.reason);Object.entries(object(o.target_weights)).forEach(([k,v])=>{if(!/^[1-9]\d*$/.test(k))fail();decimal(v)});if(o.status==='ready')array(o.inputs,8,v=>{const x=object(v);integer(x.security_id);dates(x.window_start);dates(x.window_end);integer(x.sample_count);decimal(x.raw_latest_close);decimal(x.adjusted_latest_close);if(typeof x.selected!=='boolean')fail();text(x.action_basis);['momentum_return','moving_average','deviation','adjusted_first_close','entry_deviation','exit_deviation'].forEach(k=>{if(x[k]!==undefined)decimal(x[k])})})}
function fill(v:unknown){const o=object(v);dates(o.date);dates(o.signal_date);if((o.signal_date as string)>=(o.date as string))fail();integer(o.security_id);choice(o.side,['buy','sell']);['quantity','price','notional','fee','cash_after'].forEach(k=>decimal(o[k]))}
function rejection(v:unknown){const o=object(v);dates(o.date);dates(o.signal_date);integer(o.security_id);text(o.reason);if(o.quantity!==undefined)decimal(o.quantity)}
function actionEvent(v:unknown){const o=object(v);dates(o.date);integer(o.security_id);choice(o.kind,['split','cash_dividend']);decimal(o.eligible_quantity);['ratio','amount'].forEach(k=>{if(o[k]!==undefined)decimal(o[k])});if(o.available_date!==undefined)dates(o.available_date)}
function result(v:unknown){const o=object(v);metrics(o.metrics);array(o.equity,600,equity);array(o.signals,600,signal);array(o.fills,4800,fill);array(o.rejections,14400,rejection);array(o.actions,100,actionEvent)}
export function validateRunSummary(v:unknown):RunSummary{const o=envelope(v);integer(o.strategy_id);integer(o.dataset_id);fp(o.fingerprint);text(o.status);text(o.engine_version);strategyBody(o.strategy);strings(o.warnings);metrics(o.metrics);dates(o.holdout_start);return v as RunSummary}
export function validateAnnotation(v:unknown,runId:number):Annotation{const o=envelope(v);if(o.run_id!==runId)fail();choice(o.kind,['review','research']);text(o.status);if(o.research_project_id!==null)integer(o.research_project_id);if(o.kind==='review'){text(o.note,4000,true);text(o.hypothesis,4000,true);choice(o.status,['unreviewed','reviewed','invalidated']);if(typeof o.invalidation_flag!=='boolean')fail()}else{choice(o.status,['completed','failed']);fp(o.input_fingerprint);text(o.model_name);text(o.prompt_version);text(o.ai_label);const s=object(o.input_snapshot);if(s.run_id!==runId)fail();fp(s.run_fingerprint);text(s.scope);array(s.metrics,100,v=>{const m=object(v);text(m.key);nullableDecimal(m.value);text(m.unit);dates(m.as_of)});array(s.ledger,2,object);if(o.status==='completed'){const r=object(o.research);text(r.executive_summary);const evidence=new Set((s.ledger as Record<string,unknown>[]).map(e=>e.evidence_id)),metricKeys=new Set((s.metrics as Record<string,unknown>[]).map(m=>m.key));array(r.claims,30,v=>{const c=object(v);choice(c.kind,['fact','inference','hypothesis']);text(c.statement);strings(c.evidence_ids,30);strings(c.counter_evidence_ids,30);[...c.evidence_ids as string[],...c.counter_evidence_ids as string[]].forEach(id=>{if(!evidence.has(id))fail()});array(c.metric_refs,30,v=>{const m=object(v);text(m.metric_key);if(!metricKeys.has(m.metric_key))fail();nullableDecimal(m.reported_value)})});['risks','data_gaps','next_checks'].forEach(k=>strings(r[k],30));array(r.invalidation_conditions,20,object);array(o.diagnostics,30,v=>{const d=object(v);integer(d.claim_index,0);if((d.claim_index as number)>=(r.claims as unknown[]).length)fail();choice(d.reference_check,['passed']);choice(d.numeric_check,['matched','mismatch','not_reported']);choice(d.semantic_support,['not_assessed']);strings(d.codes)});const review=object(o.model_review);choice(review.status,['not_requested','available','unavailable']);text(review.label);if(review.status==='available')array(review.claims,30,v=>{const c=object(v);integer(c.claim_index,0);if((c.claim_index as number)>=(r.claims as unknown[]).length)fail();choice(c.support,['supported','unsupported','uncertain']);text(c.explanation)})}else text(o.error_code)}if(o.kind==='research'&&o.status==='completed'){const r=object(o.model_review);if(r.status==='available'){const claims=r.claims as {claim_index:number}[];if(new Set(claims.map(c=>c.claim_index)).size!==claims.length)return {...o,model_review:{status:'unavailable',label:r.label}} as unknown as Annotation}}return v as Annotation}
export function validateRun(v:unknown,id?:number):Run{const o=envelope(v,id);integer(o.strategy_id);integer(o.dataset_id);fp(o.fingerprint);fp(o.dataset_fingerprint);fp(o.strategy_fingerprint);text(o.status);text(o.engine_version);strategyBody(o.strategy);strings(o.warnings);const a=object(o.assumptions);decimal(a.initial_cash);costs(a.costs);array(a.instrument_rules,8,instrument);text(a.calendar);text(a.return_label);text(a.execution);result(o.result);result(o.baseline);const h=object(o.holdout);dates(h.start_date);decimal(h.initial_cash);text(h.warmup);result(h.result);result(h.baseline);const r=object(o.robustness);text(r.status);text(r.segment);text(r.interpretation);array(r.parameter_neighbors,2,v=>{const x=object(v);text(x.parameter);if(typeof x.value==='number')integer(x.value);else decimal(x.value);metrics(x.metrics)});const d=object(r.doubled_costs);costs(d.costs);metrics(d.metrics);if(o.annotations!==undefined){const annotations=array(o.annotations,100,object).map(x=>validateAnnotation(x,o.id as number));annotations.forEach(a=>{if(a.kind==='research'&&a.input_snapshot?.run_fingerprint!==o.fingerprint)fail()});return {...o,annotations} as unknown as Run}return v as Run}
function state(v:unknown){const s=object(v);['cash','fees_paid','traded_notional'].forEach(k=>decimal(s[k]));dates(s.last_date);Object.values(object(s.positions)).forEach(v=>array(v,600,x=>{const lot=object(x);decimal(lot.quantity);dates(lot.buy_date)}));Object.values(object(s.last_prices)).forEach(decimal);array(s.receivables,100,v=>{const r=object(v);decimal(r.amount);dates(r.available_date)});strings(s.applied_actions);if(s.pending_signal!==null)signal(s.pending_signal)}
export function validateAccount(v:unknown,id?:number):Account{const o=envelope(v,id);integer(o.strategy_id);integer(o.dataset_id);integer(o.version);text(o.name,100);text(o.engine_version);fp(o.strategy_fingerprint);strategyBody(o.strategy);decimal(o.initial_cash);costs(o.costs);dates(o.activation_date);dates(o.snapshot_as_of);choice(o.status,['awaiting_future_data','active']);strings(o.warnings);state(o.state);if(o.steps!==undefined)array(o.steps,600,v=>{const s=envelope(v);if(s.account_id!==o.id)fail();dates(s.session_date);equity(s.equity);signal(s.signal);array(s.fills,8,fill);array(s.rejections,24,rejection);array(s.actions,100,actionEvent);state(s.state)});return v as Account}
export function validateComparison(v:unknown,runId:number):Comparison{const o=object(v);if(o.run_id!==runId)fail();dates(o.signal_date);text(o.target_status);decimal(o.known_valuation_total);ids(o.missing_security_ids,1000);strings(o.warnings);text(o.interpretation);array(o.rows,1000,v=>{const r=object(v);integer(r.security_id);decimal(r.quantity);['saved_market_value','actual_weight','target_weight'].forEach(k=>nullableDecimal(r[k]));if(r.quote_as_of!==null)text(r.quote_as_of)});return v as Comparison}
export function validateSummary(v:unknown):Summary{const o=object(v);['accounts','awaiting_future_data','active_accounts','failed_runs'].forEach(k=>integer(o[k],0));if(o.latest_account_session!==null)dates(o.latest_account_session);text(o.window);choice(o.mode,['paper_only']);return v as Summary}
export function validateTemplates(v:unknown):Templates{const o=object(v);const a=array(o.templates,3,v=>{const t=object(v);choice(t.key,['etf_momentum','ma_trend','etf_mean_reversion']);text(t.name);strings(t.instrument_types,3);Object.values(object(t.parameters)).forEach(v=>{const p=object(v);['minimum','maximum','default'].forEach(k=>typeof p[k]==='number'?integer(p[k],0):decimal(p[k]))})});if(a.length!==3||new Set(a.map(v=>object(v).key)).size!==3)fail();object(o.source_contract);const limits=object(o.limits);['max_instruments','max_sessions','max_json_bytes'].forEach(k=>integer(limits[k]));text(o.mode);return v as Templates}
async function request<T>(path:string,validate:(v:unknown)=>T,signal?:AbortSignal,body?:unknown):Promise<T>{let response:Response;try{response=await fetch(`/api/quant/${path}`,{signal,method:body===undefined?'GET':'POST',...(body===undefined?{}:{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})})}catch(e){if(signal?.aborted)throw e;throw new QuantError('network')}if(!response.ok)throw new QuantError(response.status===409?'conflict':response.status===422?'invalid':response.status===404?'missing':response.status===502?'source':'request');let value:unknown;try{value=await response.json()}catch{throw new QuantError('payload')}if(signal?.aborted)throw new DOMException('Aborted','AbortError');return validate(value)}
const id=(v:number)=>integer(v)
const list=<T>(v:unknown,validate:(v:unknown)=>T):T[]=>{const values=array(v,20,object).map(item=>validate(item));const keys=values.map(v=>object(v).id);if(new Set(keys).size!==keys.length)fail();return values}
export const fetchQuantTemplates=(s?:AbortSignal)=>request('templates',validateTemplates,s)
export const fetchQuantDatasets=(s?:AbortSignal)=>request('datasets?limit=20',v=>list(v,validateDataset),s)
export const fetchQuantStrategies=(security:number|null=null,s?:AbortSignal)=>request(`strategies?limit=20${security===null?'':`&security_id=${security}`}`,v=>list(v,validateStrategy),s)
export const fetchQuantRuns=(security:number|null=null,s?:AbortSignal)=>request(`runs?limit=20${security===null?'':`&security_id=${security}`}`,v=>list(v,validateRunSummary),s)
export const fetchQuantAccounts=(s?:AbortSignal)=>request('accounts?limit=20',v=>list(v,validateAccount),s)
export const fetchQuantSummary=(s?:AbortSignal)=>request('summary',validateSummary,s)
export const importQuantDataset=(b:DatasetImport,s?:AbortSignal)=>request('datasets/import',validateDataset,s,b)
export const acquireQuantDataset=(b:Acquire,s?:AbortSignal)=>request('datasets/acquire',validateDataset,s,b)
export const saveQuantStrategy=(b:StrategyBody,s?:AbortSignal)=>request('strategies',validateStrategy,s,b)
export const createQuantRun=(b:RunBody,s?:AbortSignal)=>request('runs',validateRun,s,b)
export const fetchQuantRun=(identifier:number,s?:AbortSignal)=>{id(identifier);return request(`runs/${identifier}`,v=>validateRun(v,identifier),s)}
export const createQuantAccount=(b:RunBody&{name:string},s?:AbortSignal)=>request('accounts',validateAccount,s,b)
export const fetchQuantAccount=(identifier:number,s?:AbortSignal)=>{id(identifier);return request(`accounts/${identifier}`,v=>validateAccount(v,identifier),s)}
export const advanceQuantAccount=(identifier:number,b:{expected_version:number;dataset_id:number},s?:AbortSignal)=>{id(identifier);return request(`accounts/${identifier}/advance`,v=>validateAccount(v,identifier),s,b)}
export const generateQuantResearch=(identifier:number,critique:boolean,s?:AbortSignal)=>{id(identifier);return request(`runs/${identifier}/research`,v=>validateAnnotation(v,identifier),s,{critique})}
export const reviewQuantRun=(identifier:number,b:ReviewBody,s?:AbortSignal)=>{id(identifier);return request(`runs/${identifier}/review`,v=>validateAnnotation(v,identifier),s,b)}
export const fetchQuantComparison=(identifier:number,s?:AbortSignal)=>{id(identifier);return request(`runs/${identifier}/holdings-comparison`,v=>validateComparison(v,identifier),s)}
export type {Costs}
