import type { ResearchClaim, ResearchCondition } from './research'
export type TemplateKey = 'etf_momentum' | 'ma_trend' | 'etf_mean_reversion'
export type Coverage = 'unknown' | 'declared_complete' | 'declared_none'
export interface Instrument {security_id:number;market:'SH'|'SZ';code:string;name:string;instrument_type:'a_share'|'etf'|'lof';lot_size:number;settlement_lag:number;limit_pct:string|null}
export interface Costs {commission_rate:string;minimum_commission:string;sell_tax:string;slippage:string;volume_cap:string}
export interface Template {key:TemplateKey;name:string;parameters:Record<string,{minimum:number|string;maximum:number|string;default:number|string}>;instrument_types:string[]}
export interface Templates {templates:Template[];source_contract:Record<string,unknown>;limits:{max_instruments:number;max_sessions:number;max_json_bytes:number};mode:string}
export interface Dataset {id:number;fingerprint:string;created_at:string;name:string;source:string;retrieved_at:string;price_basis:'raw';currency:'CNY';volume_unit:'shares';instruments:Instrument[];corporate_action_coverage:Coverage;calendar_provenance:string;warnings:string[];calendar?:string[];bars?:Bar[];actions?:Action[];bar_count?:number;session_count?:number;coverage_start?:string;coverage_end?:string}
export interface Bar {security_id:number;date:string;open:string;high:string;low:string;close:string;volume:string}
export interface Action {security_id:number;date:string;kind:'split'|'cash_dividend';value:string;cash_available_date?:string|null}
export interface DatasetImport {name:string;source:string;retrieved_at:string;price_basis:'raw';currency:'CNY';volume_unit:'shares';calendar:string[];instruments:Instrument[];bars:Bar[];corporate_action_coverage:Coverage;actions:Action[];calendar_provenance?:string}
export interface Acquire {name:string;instruments:Instrument[];start_date:string;end_date:string;corporate_action_coverage:Coverage;actions:Action[];calendar?:string[]}
export interface StrategyBody {name:string;template:TemplateKey;universe:number[];parameters:Record<string,number|string>;max_exposure:string;parent_id?:number|null}
export interface Strategy extends StrategyBody {id:number;fingerprint:string;created_at:string;parent_id:number|null}
export interface Metrics {net_return:string;gross_return?:string;annualized_sample_volatility:string|null;max_drawdown:string;turnover:string;average_exposure:string;fees_paid:string;sample_count:number;end_nav:string}
export interface Equity {date:string;nav:string;cash:string;exposure:string;stale_security_ids:number[]}
export interface SignalInput {security_id:number;window_start:string;window_end:string;sample_count:number;raw_latest_close:string;adjusted_latest_close:string;selected:boolean;action_basis:string;adjusted_first_close?:string;momentum_return?:string;moving_average?:string;deviation?:string;entry_deviation?:string;exit_deviation?:string}
export interface Signal {date:string;status:'ready'|'warmup'|'unavailable';target_weights:Record<string,string>;reason:string;inputs?:SignalInput[]}
export interface Fill {date:string;signal_date:string;security_id:number;side:'buy'|'sell';quantity:string;price:string;notional:string;fee:string;cash_after:string}
export interface Rejection {date:string;signal_date:string;security_id:number;side?:string;quantity?:string;reason:string}
export interface ActionEvent {date:string;security_id:number;kind:string;ratio?:string;amount?:string;available_date?:string;eligible_quantity:string}
export interface Result {metrics:Metrics;equity:Equity[];signals:Signal[];fills:Fill[];rejections:Rejection[];actions:ActionEvent[]}
export interface RunSummary {id:number;strategy_id:number;dataset_id:number;fingerprint:string;created_at:string;status:string;engine_version:string;strategy:StrategyBody;warnings:string[];metrics:Metrics;holdout_start:string}
export interface Run extends Omit<RunSummary,'metrics'|'holdout_start'> {dataset_fingerprint:string;strategy_fingerprint:string;assumptions:{initial_cash:string;costs:Costs;instrument_rules:Instrument[];calendar:string;corporate_action_coverage:Coverage;return_label:string;execution:string;[key:string]:unknown};result:Result;baseline:Result;holdout:{start_date:string;initial_cash:string;warmup:string;result:Result;baseline:Result};robustness:{status:string;segment:string;interpretation:string;parameter_neighbors:{parameter:string;value:number|string;metrics:Metrics}[];doubled_costs:{costs:Costs;metrics:Metrics}};annotations?:Annotation[]}
export interface RunBody {strategy_id:number;dataset_id:number;initial_cash:string;costs:Costs;holdout_date?:string|null}
export interface PaperState {cash:string;positions:Record<string,{quantity:string;buy_date:string}[]>;last_prices:Record<string,string>;receivables:{amount:string;available_date:string}[];applied_actions:string[];pending_signal:Signal|null;last_date:string;fees_paid:string;traded_notional:string}
export interface Step {id:number;account_id:number;session_date:string;created_at:string;equity:Equity;signal:Signal;fills:Fill[];rejections:Rejection[];actions:ActionEvent[];state:PaperState}
export interface Account {id:number;strategy_id:number;dataset_id:number;created_at:string;version:number;name:string;strategy:StrategyBody;strategy_fingerprint:string;engine_version:string;initial_cash:string;costs:Costs;activation_date:string;snapshot_as_of:string;status:'awaiting_future_data'|'active';warnings:string[];state:PaperState;steps?:Step[]}
export interface Annotation {id:number;run_id:number;kind:'review'|'research';created_at:string;research_project_id:number|null;status:string;note?:string;hypothesis?:string;invalidation_flag?:boolean;linked_project_snapshot?:{id:number;version:number;question:string;hypothesis:string|null;security_id:number};research?:{executive_summary:string;claims:ResearchClaim[];risks:string[];data_gaps:string[];next_checks:string[];invalidation_conditions:ResearchCondition[]};diagnostics?:{claim_index:number;reference_check:string;numeric_check:string;semantic_support:string;codes:string[]}[];model_review?:{status:string;label:string;claims?:{claim_index:number;support:string;explanation:string}[]};input_snapshot?:{run_id:number;run_fingerprint:string;scope:string;metrics:{key:string;value:string|null;status:string;unit:string;as_of:string}[];ledger:Record<string,unknown>[];[key:string]:unknown};input_fingerprint?:string;model_name?:string;prompt_version?:string;error_code?:string;ai_label?:string}
export interface ReviewBody {status:'unreviewed'|'reviewed'|'invalidated';note:string;hypothesis:string;research_project_id:number|null}
export interface Comparison {run_id:number;signal_date:string;target_status:string;rows:{security_id:number;quantity:string;saved_market_value:string|null;quote_as_of:string|null;actual_weight:string|null;target_weight:string|null}[];known_valuation_total:string;missing_security_ids:number[];interpretation:string;warnings:string[]}
export interface Summary {accounts:number;awaiting_future_data:number;active_accounts:number;latest_account_session:string|null;failed_runs:number;window:string;mode:string}
