// Synthetic contract fixtures. These are test data, not product performance.
import type {Account,Annotation,Comparison,Dataset,Metrics,Result,Run,RunSummary,Strategy,Summary,Templates} from '../types/quant'
export const quantFingerprint='a'.repeat(64)
export const quantCosts={commission_rate:'0.0003',minimum_commission:'5',sell_tax:'0.0005',slippage:'0.0005',volume_cap:'0.05'}
export const quantInstrument={security_id:7,market:'SH' as const,code:'510300',name:'Synthetic ETF',instrument_type:'etf' as const,lot_size:100,settlement_lag:1,limit_pct:'0.10'}
export const quantCalendar=['2026-01-05','2026-01-06','2026-01-07','2026-01-08','2026-01-09','2026-01-12']
export const quantDataset:Dataset={id:1,fingerprint:quantFingerprint,created_at:'2026-01-13T00:00:00Z',name:'Synthetic raw snapshot',source:'synthetic_contract',retrieved_at:'2026-01-13T00:00:00Z',price_basis:'raw',currency:'CNY',volume_unit:'shares',instruments:[quantInstrument],corporate_action_coverage:'unknown',calendar_provenance:'user_declared_observed_sessions',warnings:['unknown_corporate_actions_research_price_return_only'],calendar:quantCalendar,bars:quantCalendar.map(date=>({security_id:7,date,open:'4.0000000000000000001',high:'4.1',low:'3.9',close:'4.05',volume:'1000000'})),actions:[]}
export const quantDatasetSummary:Dataset={...quantDataset,calendar:undefined,bars:undefined,actions:undefined,bar_count:6,session_count:6,coverage_start:quantCalendar[0],coverage_end:quantCalendar[5]}
export const quantStrategy:Strategy={id:1,parent_id:null,fingerprint:quantFingerprint,created_at:'2026-01-13T00:00:00Z',name:'Synthetic trend',template:'ma_trend',universe:[7],parameters:{ma_window:2,rebalance_every:1},max_exposure:'1'}
export const quantMetrics:Metrics={net_return:'0.012345678901234567890123',gross_return:'0.013',annualized_sample_volatility:null,max_drawdown:'0.01',turnover:'1',average_exposure:'0.5',fees_paid:'5',sample_count:6,end_nav:'101234.5678901234567890123'}
export const quantResult:Result={metrics:quantMetrics,equity:quantCalendar.map(date=>({date,nav:'100000',cash:'100000',exposure:'0',stale_security_ids:[]})),signals:[{date:quantCalendar[0],status:'warmup',target_weights:{},reason:'insufficient_prior_closes'},{date:quantCalendar[1],status:'ready',reason:'ma_trend',target_weights:{'7':'1'},inputs:[{security_id:7,window_start:quantCalendar[0],window_end:quantCalendar[1],sample_count:2,raw_latest_close:'4.05',adjusted_latest_close:'4.05',selected:true,action_basis:'declared_actions_known_at_signal_date_only',moving_average:'4',deviation:'0.0125'}]}],fills:[{date:quantCalendar[2],signal_date:quantCalendar[1],security_id:7,side:'buy',quantity:'100',price:'4.05',notional:'405',fee:'5',cash_after:'99590'}],rejections:[{date:quantCalendar[2],signal_date:quantCalendar[1],security_id:7,reason:'volume_cap_partial',quantity:'100',side:'buy'}],actions:[]}
export const quantRun:Run={id:1,strategy_id:1,dataset_id:1,fingerprint:quantFingerprint,created_at:'2026-01-13T00:00:00Z',status:'completed',engine_version:'quant-test',strategy:quantStrategy,dataset_fingerprint:quantFingerprint,strategy_fingerprint:quantFingerprint,warnings:quantDataset.warnings,assumptions:{initial_cash:'100000',costs:quantCosts,instrument_rules:[quantInstrument],calendar:'user_declared_observed_sessions',corporate_action_coverage:'unknown',return_label:'research_price_return',execution:'close_signal_next_session_open'},result:quantResult,baseline:quantResult,holdout:{start_date:quantCalendar[4],initial_cash:'100000',warmup:'prior_closes_only_independent_cash',result:quantResult,baseline:quantResult},robustness:{status:'diagnostic',segment:'same_chronological_holdout',interpretation:'diagnostic_not_optimized_alpha',parameter_neighbors:[{parameter:'ma_window',value:3,metrics:quantMetrics}],doubled_costs:{costs:quantCosts,metrics:quantMetrics}},annotations:[]}
export const quantRunSummary:RunSummary={...quantRun,metrics:quantMetrics,holdout_start:quantCalendar[4]}
export const quantAccount:Account={id:1,strategy_id:1,dataset_id:1,created_at:'2026-01-13T00:00:00Z',version:1,name:'Synthetic paper',strategy:quantStrategy,strategy_fingerprint:quantFingerprint,engine_version:'quant-test',initial_cash:'100000',costs:quantCosts,activation_date:'2026-01-13',snapshot_as_of:quantCalendar[5],status:'awaiting_future_data',warnings:quantDataset.warnings,state:{cash:'100000',positions:{},last_prices:{},receivables:[],applied_actions:[],pending_signal:quantResult.signals[1],last_date:quantCalendar[5],fees_paid:'0',traded_notional:'0'},steps:[]}
export const quantTemplates:Templates={templates:[{key:'etf_momentum',name:'ETF momentum rotation',parameters:{lookback:{minimum:2,maximum:252,default:20},top_k:{minimum:1,maximum:8,default:1},rebalance_every:{minimum:1,maximum:60,default:5}},instrument_types:['etf']},{key:'ma_trend',name:'Moving-average trend',parameters:{ma_window:{minimum:2,maximum:252,default:20},rebalance_every:{minimum:1,maximum:60,default:1}},instrument_types:['a_share','etf','lof']},{key:'etf_mean_reversion',name:'ETF mean reversion',parameters:{ma_window:{minimum:2,maximum:252,default:20},rebalance_every:{minimum:1,maximum:60,default:1},entry_deviation:{minimum:'-0.5',maximum:'-0.001',default:'-0.05'},exit_deviation:{minimum:'0',maximum:'0.5',default:'0'}},instrument_types:['etf']}],source_contract:{source_key:'eastmoney',native_request:{klt:'101',fqt:'0'},volume_unit:'shares'},limits:{max_instruments:8,max_sessions:600,max_json_bytes:2000000},mode:'research_backtest_and_forward_paper_only'}
export const quantComparison:Comparison={run_id:1,signal_date:quantCalendar[1],target_status:'ready',rows:[{security_id:7,quantity:'10.00000000000000001',saved_market_value:'40',quote_as_of:'2026-01-12T08:00:00Z',actual_weight:'1',target_weight:'1'}],known_valuation_total:'40',missing_security_ids:[],interpretation:'local_saved_holdings_informational_only_no_orders',warnings:['weights_over_known_valuations_only']}
export const quantSummary:Summary={accounts:1,awaiting_future_data:1,active_accounts:0,latest_account_session:quantCalendar[5],failed_runs:0,window:'latest_100_saved_objects',mode:'paper_only'}
export const quantReview:Annotation={id:1,run_id:1,kind:'review',created_at:'2026-01-13T00:00:00Z',research_project_id:null,status:'reviewed',note:'Synthetic review note',hypothesis:'Synthetic falsifiable condition',invalidation_flag:false}
export const quantResearch:Annotation={id:2,run_id:1,kind:'research',created_at:'2026-01-13T00:00:00Z',research_project_id:null,status:'completed',research:{executive_summary:'Synthetic frozen explanation',claims:[{kind:'inference',statement:'Synthetic evidence does not certify alpha.',evidence_ids:['experiment:1'],counter_evidence_ids:[],metric_refs:[{metric_key:'full.net_return',reported_value:quantMetrics.net_return}]}],risks:['Synthetic limitation'],data_gaps:[],next_checks:['Extend observed sample'],invalidation_conditions:[]},diagnostics:[{claim_index:0,reference_check:'passed',numeric_check:'matched',semantic_support:'not_assessed',codes:[]}],model_review:{status:'not_requested',label:'model_review_not_verification'},input_snapshot:{run_id:1,run_fingerprint:quantFingerprint,scope:'frozen_experiment_only_no_actual_holdings',metrics:[{key:'full.net_return',value:quantMetrics.net_return,status:'ready',unit:'fraction',as_of:quantCalendar[5]}],ledger:[{evidence_id:'experiment:1'},{evidence_id:'robustness:1'}]},input_fingerprint:quantFingerprint,model_name:'synthetic',prompt_version:'test',ai_label:'model_inference_not_trading_signal_or_verification'}
