import {fireEvent,render,screen,waitFor} from '@testing-library/react'
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest'
import App from './App'
import {DEFAULT_HOMEPAGE_SETTINGS,HOMEPAGE_SETTINGS_STORAGE_KEY} from './homepageSettings'
import * as quant from './api/quant'
import {quantAccount,quantDatasetSummary,quantStrategy,quantSummary,quantTemplates} from './test/quantFixtures'
import {securityFixture,jsonResponse} from './test/dataCenterFixtures'
vi.mock('./api/quant',async original=>({...await original<typeof quant>(),fetchQuantSummary:vi.fn(),fetchQuantTemplates:vi.fn(),fetchQuantStrategies:vi.fn(),fetchQuantDatasets:vi.fn(),fetchQuantRuns:vi.fn(),fetchQuantAccounts:vi.fn()}))
vi.mock('./api/indicators',()=>({fetchSecurityIndicators:vi.fn().mockImplementation(async(id:number)=>({security_id:id,instrument_type:'etf',metrics:[],data_context:{}})),fetchHoldingsIndicators:vi.fn().mockResolvedValue({positions:[],metrics:[],missing_price_security_ids:[],valuation_complete:true,denominator:'known_valued_positions_only',warnings:[]})}))
const security={security_id:7,market:'SH',code:'510300',name:'Synthetic ETF',industry:'ETF',status:'active'}
const detail={security,price_context:[],price_history:[],financial_metrics:[],company_profile:null,announcements:[],news:[]}
beforeEach(()=>{window.localStorage.clear();window.localStorage.setItem(HOMEPAGE_SETTINGS_STORAGE_KEY,JSON.stringify({...DEFAULT_HOMEPAGE_SETTINGS,showSpotlight:false,showMacroPanel:false,autoRefreshEnabled:false,autoSyncEnabled:false}));vi.clearAllMocks();vi.mocked(quant.fetchQuantSummary).mockResolvedValue(quantSummary);vi.mocked(quant.fetchQuantTemplates).mockResolvedValue(quantTemplates);vi.mocked(quant.fetchQuantStrategies).mockResolvedValue([quantStrategy]);vi.mocked(quant.fetchQuantDatasets).mockResolvedValue([quantDatasetSummary]);vi.mocked(quant.fetchQuantRuns).mockResolvedValue([]);vi.mocked(quant.fetchQuantAccounts).mockResolvedValue([quantAccount]);vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL)=>{const url=String(input);if(url==='/api/watchlist/items')return jsonResponse([{...security,last_price:null,change_percent:null,snapshot_time:null}]);if(url==='/api/homepage/overview')return jsonResponse({indexes:[],macro:[],warnings:[],updated_at:null});if(url.includes('/api/homepage/ai-labels'))return jsonResponse({items:[]});if(url==='/api/stocks/7')return jsonResponse(detail);if(url.includes('/api/holdings'))return jsonResponse([{holding_id:1,security_id:7,security,quantity:'10',average_cost:'4',notes:'Saved note',target_horizon:null}]);if(url.includes('/api/ai/history'))return jsonResponse([]);if(url.includes('/api/data-center/securities/7'))return jsonResponse(securityFixture(7));if(url.includes('/api/research/projects?'))return jsonResponse([]);return jsonResponse({items:[]})}))})
afterEach(()=>{vi.unstubAllGlobals();window.localStorage.clear()})
describe('App strategy navigation',()=>{
 it('retains real detail holdings and strategy drafts across global workspace open/close',async()=>{render(<App/>);const item=await screen.findByRole('button',{name:'View details for Synthetic ETF'});fireEvent.click(item);await screen.findByRole('button',{name:'Related strategies and experiments'});fireEvent.click(screen.getByRole('tab',{name:'Holdings & AI'}));await waitFor(()=>expect(screen.getByLabelText('Quantity')).toHaveValue('10'));fireEvent.change(screen.getByLabelText('Quantity'),{target:{value:'23.000000000001'}});fireEvent.change(screen.getByLabelText('Notes'),{target:{value:'Retained holding draft'}});const origin=screen.getByRole('button',{name:'Related strategies and experiments'});origin.focus();fireEvent.click(origin);await screen.findByRole('heading',{name:'Strategy workspace'});await screen.findByRole('button',{name:'Synthetic trend · #1'});expect(quant.fetchQuantStrategies).toHaveBeenLastCalledWith(7,expect.any(AbortSignal));expect(screen.queryByRole('textbox',{name:'Quantity'})).not.toBeInTheDocument();expect(screen.getByLabelText('Quantity').closest('[inert]')).not.toBeNull();fireEvent.change(screen.getByLabelText('Strategy name'),{target:{value:'Retained strategy draft'}});fireEvent.click(screen.getByRole('button',{name:'Back to investment board'}));await waitFor(()=>expect(screen.getByLabelText('Quantity')).toHaveValue('23.000000000001'));expect(screen.getByLabelText('Notes')).toHaveValue('Retained holding draft');expect(origin).toHaveFocus();fireEvent.click(screen.getByRole('tab',{name:'Evidence research'}));await screen.findByRole('textbox',{name:'Research question'});fireEvent.change(screen.getByRole('textbox',{name:'Research question'}),{target:{value:'Retained evidence research draft'}});fireEvent.click(screen.getByRole('button',{name:'Strategy workspace'}));await screen.findByRole('heading',{name:'Strategy workspace'});expect(screen.getByLabelText('Strategy name')).toHaveValue('Retained strategy draft');fireEvent.click(screen.getByRole('button',{name:'Back to investment board'}));expect(screen.getByRole('textbox',{name:'Research question'})).toHaveValue('Retained evidence research draft');fireEvent.click(screen.getByRole('tab',{name:'Holdings & AI'}));expect(screen.getByLabelText('Quantity')).toHaveValue('23.000000000001')})
 it('shows saved paper summary and retains watchlist filter after global strategy navigation',async()=>{render(<App/>);await screen.findByRole('button',{name:'View details for Synthetic ETF'});expect(await screen.findByText(/1 paper accounts/)).toHaveTextContent('1 awaiting future data');const filter=screen.getByLabelText('Filter watchlist');fireEvent.change(filter,{target:{value:'510300'}});fireEvent.click(screen.getByRole('button',{name:'Strategies and paper'}));await screen.findByRole('heading',{name:'Strategy workspace'});fireEvent.click(screen.getByRole('button',{name:'Back to investment board'}));expect(screen.getByLabelText('Filter watchlist')).toHaveValue('510300')})
})
